//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 12/17/2009 11:29:32 PM
namespace InRetail.ProductCatalog.Web
{
    
    /// <summary>
    /// There are no comments for ProductCatalogContainer in the schema.
    /// </summary>
    public partial class ProductCatalogContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ProductCatalogContainer object using the connection string found in the 'ProductCatalogContainer' section of the application configuration file.
        /// </summary>
        public ProductCatalogContainer() : 
                base("name=ProductCatalogContainer", "ProductCatalogContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ProductCatalogContainer object.
        /// </summary>
        public ProductCatalogContainer(string connectionString) : 
                base(connectionString, "ProductCatalogContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ProductCatalogContainer object.
        /// </summary>
        public ProductCatalogContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ProductCatalogContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ProductDetailViewModels in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ProductDetailViewModel> ProductDetailViewModels
        {
            get
            {
                if ((this._ProductDetailViewModels == null))
                {
                    this._ProductDetailViewModels = base.CreateQuery<ProductDetailViewModel>("[ProductDetailViewModels]");
                }
                return this._ProductDetailViewModels;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ProductDetailViewModel> _ProductDetailViewModels;
        /// <summary>
        /// There are no comments for ProductDetailViewModels in the schema.
        /// </summary>
        public void AddToProductDetailViewModels(ProductDetailViewModel productDetailViewModel)
        {
            base.AddObject("ProductDetailViewModels", productDetailViewModel);
        }
    }
    /// <summary>
    /// There are no comments for ProductCatalogModel.ProductDetailViewModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ProductCatalogModel", Name="ProductDetailViewModel")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ProductDetailViewModel : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ProductDetailViewModel object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static ProductDetailViewModel CreateProductDetailViewModel(global::System.Guid id)
        {
            ProductDetailViewModel productDetailViewModel = new ProductDetailViewModel();
            productDetailViewModel.Id = id;
            return productDetailViewModel;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
    }
}
